---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-person-detector
  labels:
    app.kubernetes.io/name: ros2-person-detector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ros2-person-detector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ros2-person-detector
    spec:
      hostNetwork: true
      containers:
      - name: ros2-person-detector
        image: luizcarloscf/ros2-person-detector:test
        imagePullPolicy: Always
        command: ["/entrypoint.sh"]
        args: ["ros2", "launch", "yolov8_ros2", "person_detector.launch.py"]
        securityContext:
          privileged: true
